// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fyateryvaloezbyhzeoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5YXRlcnl2YWxvZXpieWh6ZW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDAyMDAsImV4cCI6MjA2OTc3NjIwMH0.mvBwuIaoQ0w4W2p3SL2nU7LG1zbnxYaAB1lDFL0eRLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});